### ISSUE TITLE
[Feature] Add total points to results file

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1301]
**Describe the solution you'd like**
Currently when you run a test you will get a results file like this

```
---
name: cnf testsuite
status: 
points: 
exit_code: 0
items:
- name: install_script_helm
  status: passed
  points: 5
- name: install_script_helm_v2
  status: failed
  points: -1
```

A possible solution would be to use the top points field to list points one got and add a new field to list available points

```
name: cnf testsuite
status: 
points: 4
total_points: 10
exit_code: 0
items:
- name: install_script_helm
  status: passed
  points: 5
- name: install_script_helm_v2
  status: failed
  points: -1
```

This way you can easily see that you got 4 out of 10 points for this this test

**Comment by HashNuke** [comment]
@EricLo-417 We have a change in the `main` branch to output `points` and `maximum_points` to the results file. This should be available in an upcoming release if everything is good.

**Comment by agentpoyo** [comment]
Todo: Add AC for Peer Review.

**Comment by agentpoyo** [comment]
@HashNuke 

Running a category still doesn't display the total amount of points in the results file, see screenshot below:

![points_discrepancy](https://user-images.githubusercontent.com/14348948/161881471-af040971-a633-4ceb-a357-7fbca8f99c5d.png)

**Comment by agentpoyo** [comment]
@HashNuke 

Workload adds the points to the results file though:

```
root@cnf-testsuite-test1:~/cnf-testsuite# head results/cnf-testsuite-results-20220406-020836-272.yml -n 20
---
name: cnf testsuite
status: 
points: 150
exit_code: 2
items:
- name: install_script_helm
  status: passed
  points: 5
- name: helm_chart_valid
  status: passed
  points: 5
- name: helm_chart_published
  status: passed
  points: 5
- name: increase_capacity
  status: passed
  points: 10
- name: decrease_capacity
  status: passed
```

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Setup or find k8s cluster, run `cnf-config` using the sample coredns-cnf.
- [ ] When an individual test is run, the results file provides the max points in the log file.
- [ ] When a category (eg. microservice) is run, the results file provides the max points in the log file.
- [ ] When a workload is run, the results file provides the max points in the log file.

**Comment by agentpoyo** [comment]
Ignore the 20 points out of 25, there's a bug in for shared_database not running during this category or workload. #1323 

```
root@cnf-testsuite-test1:~/cnf-testsuite# ./cnf-testsuite microservice
✔️  PASSED: Image size is good 🐜 ⚖️👀
✔️  PASSED: CNF had a reasonable startup time 🚀
✔️  PASSED: Only one process type used 🐜 ⚖️👀
✔️  PASSED: Some containers exposed as a service 🐜 ⚖️👀
Microservice final score: 20 of 25
 
root@cnf-testsuite-test1:~/cnf-testsuite# cat results/cnf-testsuite-results-20220408-124721-568.yml                                  
---
name: cnf testsuite
status: 
points: 20
exit_code: 0
items:
- name: reasonable_image_size
  status: passed
  points: 5
- name: reasonable_startup_time
  status: passed
  points: 5
- name: single_process_type
  status: passed
  points: 5
- name: service_discovery
  status: passed
  points: 5
maximum_points: 25
```
