### ISSUE TITLE
[BUG] When I run `cnf-testsuite microservice`, I see 4 tests run and pass but get 20 out of 25 points

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1313]
**Describe the bug**
It appears the `shared_database` is tagged as a microservice in the embedded points file but does not run when you run `cnf-testsuite microservice`

**To Reproduce**
Setup sample-coredns-cnf CNF and then run: `./cnf-testsuite microservice`, see output below as the results shows a total of 20 points total, with the shared_database test missing as it did not run:

```
root@cnf-testsuite-test1:~/cnf-testsuite# ./cnf-testsuite microservice
✔️  PASSED: Image size is good 🐜 ⚖️👀
✔️  PASSED: CNF had a reasonable startup time 🚀
✔️  PASSED: Only one process type used 🐜 ⚖️👀
✔️  PASSED: Some containers exposed as a service 🐜 ⚖️👀
Microservice final score: 20 of 25

root@cnf-testsuite-test1:~/cnf-testsuite# cat results/cnf-testsuite-results-20220406-015205-574.yml 
---
name: cnf testsuite
status: 
points: 
exit_code: 0
items:
- name: reasonable_image_size
  status: passed
  points: 5
- name: reasonable_startup_time
  status: passed
  points: 5
- name: single_process_type
  status: passed
  points: 5
- name: service_discovery
  status: passed
  points: 5
```
Now view the embedded points file by grepping all tests with microservice tag:

```
grep -B1 microservice points.yml
- name: reasonable_image_size
  tags: microservice, dynamic, workload
- name: reasonable_startup_time 
  tags: microservice, dynamic, workload
- name: single_process_type 
  tags: microservice, dynamic, workload
- name: service_discovery
  tags: microservice, dynamic, workload
--
- name: shared_database
  tags: microservice, dynamic, workload
```

You can see, 5 tests valued at 5 points each.

**Expected behavior**
Should see 25 out of 25 if all the tests pass with shared_database as a test that runs.
