### ISSUE TITLE
[DOC] Capture latest `workload` output from console and results file output

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1352]
**Describe the request**
Capture the latest console and results file output, text based and image based.

**Comment by agentpoyo** [comment]
`cnf-testsuite setup` sample output:

```
# ./cnf-testsuite setup
Successfully created directories for cnf-testsuite
Global helm found. Version: v3.7.1
Local helm found. Version: v3.7.1
Global kubectl found. Version: 1.22
No Local kubectl version found
Global git found. Version: 2.20.1
No Local git version found
All prerequisites found.
Created cnf-testsuite namespace on the Kubernetes cluster
Setup complete
```
<img width="578" alt="Screen Shot 2022-04-12 at 2 51 39 PM" src="https://user-images.githubusercontent.com/14348948/163042437-57b60074-c9f4-4b96-bd8d-a9307d03be94.png">

`cnf-testsuite cnf_setup cnf-config` sample output:

```
# ./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml 
Successfully created directories for cnf-testsuite
cnf-testsuite namespace already exists on the Kubernetes cluster
cnf setup online mode
Successfully setup coredns
cnf setup online mode complete
```
<img width="1149" alt="Screen Shot 2022-04-12 at 2 52 21 PM" src="https://user-images.githubusercontent.com/14348948/163042623-e3e49a3b-d957-46ac-bde2-905f6d3b162e.png">

**Comment by agentpoyo** [comment]
Full `workload` text paste:

```
$  ./cnf-testsuite workload ~install_script_helm ~alpha_k8s_apis ~volume_hostpath_not_found ~database_persistence ~privileged ~non_root_user ~versioned_tag ~ip_addresses                                                                                                                                        
Successfully created directories for cnf-testsuite                                                                                                                                                                                                                                                                                                          
✔️  PASSED: Helm Chart exported_chart Lint Passed ⎈📝☑️                                                                                                                                                                                                                                                                                                       
✔️  PASSED: Published Helm Chart Found ⎈📦🌐                                                                                                                                                                                                                                                                                                                 
⏭️  SKIPPED: Helm Deploy                                                                                                                                                                                                                                                                                                                                     
✔️  PASSED: CNF compatible with both Calico and Cilium 🔓🔑                                                                                                                                                                                                                                                                                                  
✔️  PASSED: Replicas increased to 3 📦📈                                                                                                                                                                                                                                                                                                                     
✔️  PASSED: Replicas decreased to 1 📦📉                                                                                                                                                                                                                                                                                                                     
Rolling update failed on resource: coredns-coredns and container: coredns                                                                                                                                                                                                                                                                                   
✖️  FAILED: CNF Rollback Failed                                                                                                                                                                                                                                                                                                                              
✔️  PASSED: CNF for Rolling Update Passed                                                                                                                                                                                                                                                                                                                    
✔️  PASSED: CNF for Rolling Downgrade Passed                                                                                                                                                                                                                                                                                                                 
✖️  FAILED: CNF for Rolling Version Change Failed                                                                                                                                                                                                                                                                                                            
Compatibility, installability, and upgradeability final score: 43 of 65                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                            
Rescued: On resource coredns-coredns of kind Service, local storage configuration volumes not found 🖥️  💾                                                                                                                                                                                                                                                   
✔️  PASSED: local storage configuration volumes not found 🖥️  💾                                                                                                                                                                                                                                                                                              
✔️  FAILED: Elastic Volumes Not Used 🧫                                                                                                                                                                                                                                                                                                            [          ode-drain chaos test failed 🗡️💀♻️                                                                                                                                                                                                                                                                                                                           
✖️  FAILED: node_drain chaos test failed 🗡️💀♻️                                                                                                                                                                                                                                                                                                                
State final score: 4 of 25                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                            
✔️  PASSED: No containers allow a symlink attack 🔓🔑                                                                                                                                                                                                                                                                                                        
✖️  FAILED: Found containers that allow privilege escalation 🔓🔑                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
container: chaos-runner in pod: coredns-coredns-20-runner  allow privilege escalation                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                            
container :coredns in Deployment: coredns-coredns  allow privilege escalation                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                            
container :node-drain-7n3qko in Job: node-drain-7n3qko  allow privilege escalation                                                                                                                                                                                                                                                                          
Remediation: If your application does not need it, make sure the allowPrivilegeEscalation field of the securityContext is set to false.                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                            
✔️  PASSED: Containers with insecure capabilities were not found 🔓🔑                                                                                                                                                                                                                                                                                        
✔️  PASSED: Containers with dangerous capabilities were not found 🔓🔑                                                                                                                                                                                                                                                                                       
✖️  FAILED: Found containers without resource limits defined 🔓🔑                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
there are no resource limits defined for container : chaos-runner                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                            
there are no resource limits defined for container : node-drain-7n3qko
Remediation: Define LimitRange and ResourceQuota policies to limit resource usage for namespaces or nodes.
✖️  FAILED: Found resources that do not use security services 🔓🔑

Pod: coredns-coredns-20-runner does not define any linux security hardening

Workload: coredns-coredns does not define any linux security hardening

Workload: node-drain-7n3qko does not define any linux security hardening
Remediation: You can use AppArmor, Seccomp, SELinux and Linux Capabilities mechanisms to restrict containers abilities to utilize unwanted privileges.

✖️  FAILED: Ingress and Egress traffic not blocked on pods 🔓🔑

Pod: coredns-coredns-20-runner does not have ingress/egress defined

Deployment: coredns-coredns has Pods which don't have ingress/egress defined

Job: node-drain-7n3qko has Pods which don't have ingress/egress defined
Remediation: Define a network policy that restricts ingress and egress connections.

✔️  PASSED: No containers with hostPID and hostIPC privileges 🔓🔑
✔️  PASSED: Containers are running with non-root user with non-root group membership 🔓🔑
✔️  PASSED: No privileged containers were found 🔓🔑
✖️  FAILED: Found namespaces which do not have network policies defined 🔓🔑

no policy is defined for namespace default
Remediation: Define network policies or use similar network protection mechanisms.

✖️  FAILED: Found containers with mutable file systems 🔓🔑

container: chaos-runner in pod: coredns-coredns-20-runner  has  mutable filesystem

container :coredns in Deployment: coredns-coredns has  mutable filesystem

container :node-drain-7n3qko in Job: node-drain-7n3qko has  mutable filesystem
Remediation: Set the filesystem of the container to read-only when possible (POD securityContext, readOnlyRootFilesystem: true). If containers application needs to write into the filesystem, it is recommended to mount secondary filesystems for specific directories where application require write access.

✔️  PASSED: Containers do not have hostPath mounts 🔓🔑
✔️  PASSED: Container engine daemon sockets are not mounted as volumes 🔓🔑
✔️  PASSED: Services are not using external IPs 🔓🔑
✔️  PASSED: Resources are not using custom SELinux options 🔓🔑
✔️  PASSED: No restricted values found for sysctls 🔓🔑
Security final score: 49 of 110

✔️  PASSED: NodePort is not used
✔️  PASSED: HostPort is not used
✔️  PASSED: No hard-coded IP addresses found in the runtime K8s configuration
No Secret Volumes or Container secretKeyRefs found for resource: {kind: "Deployment", name: "coredns-coredns", namespace: "default"}
⏭  SKIPPED: Secrets not used 🧫

To address this issue please see the USAGE.md documentation

✖️  FAILED: Found mutable configmap(s) ⚖️
✔️  PASSED: Pods have the app.kubernetes.io/name label 🏷️✔️
✖️  FAILED: Container images are using the latest tag 🏷️❌
Pod coredns-coredns-7b54848f87-k8fsd in default namespace failed. validation error: Using a mutable image tag e.g. 'latest' is not allowed. Rule validate-image-tag failed at path /spec/containers/0/image/
Deployment coredns-coredns in default namespace failed. validation error: Using a mutable image tag e.g. 'latest' is not allowed. Rule autogen-validate-image-tag failed at path /spec/template/spec/containers/0/image/
✖️  FAILED: Resources are created in the default namespace 🏷️❌
Pod coredns-coredns-7b54848f87-k8fsd in default namespace failed. validation error: Using 'default' namespace is not allowed. Rule validate-namespace failed at path /metadata/namespace/
Deployment coredns-coredns in default namespace failed. validation error: Using 'default' namespace is not allowed for pod controllers. Rule validate-podcontroller-namespace failed at path /metadata/namespace/
Configuration final score: 18 of 41

✔️  PASSED: Resources output logs to stdout and stderr 📶☠️
⏭️  SKIPPED: Prometheus server not found 📶☠️
⏭️  SKIPPED: Prometheus traffic not configured 📶☠️
⏭️  SKIPPED: Fluentd not configured 📶☠️
⏭️  SKIPPED: Jaeger not configured ⎈🚀
Observability and diagnostics final score: 5 of 5

✔️  PASSED: Image size is good 🐜 ⚖️👀
✔️  PASSED: CNF had a reasonable startup time 🚀
✔️  PASSED: Only one process type used 🐜 ⚖️👀
✔️  PASSED: Some containers exposed as a service 🐜 ⚖️👀
Microservice final score: 20 of 25

pod-network-latency chaos test failed 🗡️💀♻️
✖️  FAILED: pod_network_latency chaos test failed 🗡️💀♻️
pod-network-corruption chaos test failed 🗡️💀♻️
✖️  FAILED: pod_network_corruption chaos test failed 🗡️💀♻️
disk-fill chaos test failed 🗡️💀♻️
✖️  FAILED: disk_fill chaos test failed 🗡️💀♻️
pod-delete chaos test failed 🗡️💀♻️
✖️  FAILED: pod_delete chaos test failed 🗡️💀♻️
pod-memory-hog chaos test failed 🗡️💀♻️
✖️  FAILED: pod_memory_hog chaos test failed 🗡️💀♻️
pod-io-stress chaos test failed 🗡️💀♻️
✖️  FAILED: pod_io_stress chaos test failed 🗡️💀♻️
✖️  SKIPPED: pod_dns_error docker runtime not found 🗡️💀♻️
Reliability, resilience, and availability final score: -6 of 45

Final workload score: 133 of 316
CNFManager::Points::Results.have been saved to results/cnf-testsuite-results-20220414-144428-412.yml
```

**Comment by agentpoyo** [comment]
Results output sample from full `workload` run:

```
---
name: cnf testsuite
status: 
points: 133
exit_code: 0
items:
- name: helm_chart_valid
  status: passed
  points: 5
- name: helm_chart_published
  status: passed
  points: 5
- name: cni_compatible
  status: passed
  points: 5
- name: increase_capacity
  status: passed
  points: 10
- name: decrease_capacity
  status: passed
  points: 10
- name: rollback
  status: failed
  points: -1
- name: rolling_update
  status: passed
  points: 5
- name: rolling_downgrade
  status: passed
  points: 5
- name: rolling_version_change
  status: failed
  points: -1
- name: no_local_volume_configuration
  status: passed
  points: 5
- name: elastic_volumes
  status: failed
  points: 0
- name: node_drain
  status: failed
  points: -1
- name: symlink_file_system
  status: passed
  points: 5
- name: privilege_escalation
  status: failed
  points: -1
- name: insecure_capabilities
  status: passed
  points: 5
- name: dangerous_capabilities
  status: passed
  points: 5
- name: resource_policies
  status: failed
  points: -1
- name: linux_hardening
  status: failed
  points: -1
- name: ingress_egress_blocked
  status: failed
  points: -1
- name: host_pid_ipc_privileges
  status: passed
  points: 5
- name: non_root_containers
  status: passed
  points: 5
- name: privileged_containers
  status: passed
  points: 5
- name: network_policies
  status: failed
  points: -1
- name: immutable_file_systems
  status: failed
  points: -1
- name: hostpath_mounts
  status: passed
  points: 5
- name: container_sock_mounts
  status: passed
  points: 5
- name: external_ips
  status: passed
  points: 5
- name: selinux_options
  status: passed
  points: 5
- name: sysctls
  status: passed
  points: 5
- name: nodeport_not_used
  status: passed
  points: 5
- name: hostport_not_used
  status: passed
  points: 5
- name: hardcoded_ip_addresses_in_k8s_runtime_configuration
  status: passed
  points: 5
- name: secrets_used
  status: skipped
  points: 0
- name: immutable_configmap
  status: failed
  points: 0
- name: require_labels
  status: passed
  points: 5
- name: latest_tag
  status: failed
  points: -1
- name: default_namespace
  status: failed
  points: -1
- name: log_output
  status: passed
  points: 5
- name: prometheus_traffic
  status: skipped
  points: 0
- name: open_metrics
  status: skipped
  points: 0
- name: routed_logs
  status: skipped
  points: 0
- name: tracing
  status: skipped
  points: 0
- name: reasonable_image_size
  status: passed
  points: 5
- name: reasonable_startup_time
  status: passed
  points: 5
- name: single_process_type
  status: passed
  points: 5
- name: service_discovery
  status: passed
  points: 5
- name: pod_network_latency
  status: failed
  points: -1
- name: pod_network_corruption
  status: failed
  points: -1
- name: disk_fill
  status: failed
  points: -1
- name: pod_delete
  status: failed
  points: -1
- name: pod_memory_hog
  status: failed
  points: -1
- name: pod_io_stress
  status: failed
  points: -1
- name: pod_dns_error
  status: skipped
  points: 0
maximum_points: 316
```
