### ISSUE TITLE
[Research] test "generate config" works as expected and document any issues

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1382]
Part of EPIC #https://github.com/cncf/cnf-testsuite/issues/1357

**Is your feature request related to a problem? Please describe.**
- The  https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md is part of the cert instructions
- It was last updated in June 2021 and may be out of date

**Describe the solution you'd like**

- [x] Review problems found on Generator Quick start, see https://hackmd.io/V70iQ_V_TIWa8imUL6AkfQ?view
- [x] Test if documentation is valid
- [ ] If not, create issue to fix bugs

---

cnf-testsuite.yml Generator Quick Start

Prereqs: You must have kubernetes cluster, curl, and helm 3.1.1 or greater on your system already.

- Generate a cnf-testsuite.yml based on a helm chart: ./cnf-testsuite generate_config config-src=stable/coredns output-file=./cnf-testsuite-test.yml
- Generate a cnf-testsuite.yml based on a helm directory: ./cnf-testsuite generate_config config-src=<your-helm-directory> output-file=./cnf-testsuite-test.yml
- Generate a cnf-testsuite.yml based on a directory of manifest files: ./cnf-testsuite generate_config config-src=<your-manifest-directory> output-file=./cnf-testsuite-test.yml
- Inspect the cnf-testsuite.yml file for accuracy

**Comment by taylor** [comment]
level of effort
- @denverwilliams 3
- @agentpoyo 2
- @lixuna na
- @taylor 2
- @wavell 2
- @HashNuke 2

**Comment by HashNuke** [comment]
Anyone that picks up this ticket, please let me know when this is done. We will have to test the support for non-default namespaces. I noticed this part of the code does not consider any namespace for the resources.

**Comment by denverwilliams** [comment]
Complected as part of https://github.com/cncf/cnf-testsuite/issues/1357

**Comment by taylor** [comment]
@HashNuke please peer review and check for the default name space things

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When i run `generate_config` using the cnf-testsuite, it should result with a valid cnf-testsuite.yml file to be used with cnf-testsuite.
- [ ] I can see the minimum requirement fields in the generated yml file.
- [ ] I can see the output here in this issue (pasted or screenshot)

**Comment by agentpoyo** [comment]
```
root@cnfqa1:~/cnf-testsuite# ./cnf-testsuite generate_config config-src=stable/coredns output-file=./cnf-testsuite-test.yml
root@cnfqa1:~/cnf-testsuite# cat cnf-testsuite-test.yml 
---
release_name: coredns-1651866414
helm_chart: stable/coredns
container_names:
- name: coredns
  rolling_update_test_tag: 1.7.1
  rolling_downgrade_test_tag: 1.7.1
  rolling_version_change_test_tag: 1.7.1
  rollback_from_tag: 1.7.1
```
