### ISSUE TITLE
[BUG] maximum points for `cert` seem incorrect in test results file from v0.29.0

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1465]
**Describe the bug**
- In a results file from v0.29.0, the maximum points showed "1471"
- If normal tests earn 5 points, and essential tests earn 100 points, and bonus points are not included in the "maximum" given the nature of "bonus" - where did the number ending in "1" come from?

**To Reproduce**
- Run cnf-testsuite 0.29.0 and view results file "maximum points", Are bonus tests included in the maximum? 
- Run cnf-testsuite 0.29.1 and view results file "maximum points" - did the results change?

**Other ideas:**
- Document the points earned with each test type

**Comment by lixuna** [comment]
Note: in https://github.com/cncf/cnf-testsuite/issues/1395#issuecomment-1122317532 v0.29.1, the maximum points is 1571 (not 1471 as above)

**Comment by wavell** [comment]
- [ ] `./cnf-testsuite cnf_setup cnf-path=./sample-cnfs/sample-ndn-privileged`
- [ ] `./cnf-testsuite cert_microservice`
- [ ] Should see 5 test messages, but only 4 as the maximum tests (the bonus test, service_discovery, should fail but not be counted in the maximum test
- [ ] Check the results file for the maximum score.  The failing / skipped / or NA bonus test should **not* increase the maximum score 
- [ ] `./cnf-testsuite cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml`
- [ ] `./cnf-testsuite cert_microservice`
- [ ] Check the results file for the maximum score.  The passing bonus test should increase the maximum score.

**Comment by agentpoyo** [comment]
```
pair@cnfdev03:~/workspace/drew/cnf-testsuite$ cat results/cnf-testsuite-results-20220608-162923-367.yml
---
name: cnf testsuite
status: 
command: /home/pair/workspace/drew/cnf-testsuite/cnf-testsuite cert_microservice
points: 110
exit_code: 0
items:
- name: reasonable_image_size
  status: passed
  type: normal
  points: 5
- name: reasonable_startup_time
  status: passed
  type: normal
  points: 5
- name: single_process_type
  status: passed
  type: essential
  points: 100
- name: service_discovery
  status: failed
  type: bonus
  points: 0
- name: shared_database
  status: skipped
  type: normal
  points: 0
maximum_points: 115
```

**Comment by agentpoyo** [comment]
![1465_cert_microservice2](https://user-images.githubusercontent.com/14348948/172713850-c5fbc81c-f1ad-418e-b75d-e97ea3a8d06b.png)


```
---
name: cnf testsuite
status: 
command: /home/pair/workspace/drew/cnf-testsuite/cnf-testsuite cert_microservice
points: 111
exit_code: 0
items:
- name: reasonable_image_size
  status: passed
  type: normal
  points: 5
- name: reasonable_startup_time
  status: passed
  type: normal
  points: 5
- name: single_process_type
  status: passed
  type: essential
  points: 100
- name: service_discovery
  status: passed
  type: bonus
  points: 1
- name: shared_database
  status: skipped
  type: normal
  points: 0
maximum_points: 116
```
