### ISSUE TITLE
[Feature] The cnf-testsuite should add the summary of the `cert` results of tests and essentials tests into the results file.

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1473]
**Is your feature request related to a problem? Please describe.**
Yes, the summary that displays on the console should also be added to the results log file for reference and accuracy of what tests passed and failed. eg. the following example below should be in the results log in valid format

```
RESULTS SUMMARY                                                                                                       
  - 37 of 56 total tests passed                                                                                                                                                                       
  - 13 of 14 essential tests passed 
 ```

**Describe the solution you'd like**
The summary should display in the results log, something like this would be sufficient at the top of the log file:

```
---
name: cnf testsuite
status: 
command: /home/eric/.mtx/automated-k8s-tests/cnf-testsuite/0.29.1/cnf-testsuite cert wait_count=100
points: 1175
exit_code: 2
total_passed: 37 of 56
essential_passed: 13 of 14
items:
- name: helm_chart_valid
  status: passed
  type: normal
  points: 5
...
```
