### ISSUE TITLE
[Research] Test coredns for the cnf-testsuite v1 cert

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1526]
## Description
* Create a cnf-testsuite config file for the latest version of coredns.
* Test coredns with the cnf-testsuite following the [v1 cert instructions](https://github.com/cncf/cnf-certification/blob/main/instructions.md).
* Share the test results on the ticket.
* Request peer review.

**Comment by agentpoyo** [comment]
2pts

**Comment by lixuna** [comment]
For the test environment use a major K8s cloud provider (eg. Google Cloud, Azure for Operators, AWS) or a vanilla K8s cluster created with Kubespray.

**Comment by agentpoyo** [comment]
> For the test environment use a major K8s cloud provider (eg. Google Cloud, Azure for Operators, AWS) or a vanilla K8s cluster created with Kubespray.

@HashNuke I got accounts we can use to setup at Google, Azuree and or AWS, or we setup a Metal Cluster using cnf-testbed.

**Comment by agentpoyo** [comment]
Using a 3 node kind cluster, here are the results (screenshots):

![1526_1](https://user-images.githubusercontent.com/14348948/183891433-3d398827-dc83-498b-bde7-faee4a21cc9e.png)

![1526_2](https://user-images.githubusercontent.com/14348948/183891459-5b9364a7-31b3-4a3e-94c9-8a96c1f066e9.png)

![1526_3](https://user-images.githubusercontent.com/14348948/183891478-9e817dbe-0ea5-47a4-ad74-0b895fab1820.png)

**Comment by agentpoyo** [comment]
Here is the config file used (cnf-testsuite.yml):

```
---
release_name: coredns
service_name: coredns-coredns 
helm_repository:
  name: stable 
  repo_url: https://cncf.gitlab.io/stable
helm_chart: stable/coredns
helm_install_namespace: cnfspace
container_names: 
  - name: coredns 
    rolling_update_test_tag: "1.9.0"
    rolling_downgrade_test_tag: 1.8.7
    rolling_version_change_test_tag: 1.9.0
    rollback_from_tag: 1.9.0
```

**Comment by agentpoyo** [comment]
Results file for 3 node kind cluster:

```
---
name: cnf testsuite
status: 
command: /root/cnf-testsuite/cnf-testsuite cert
points: 1401
exit_code: 0
items:
- name: helm_chart_valid
  status: passed
  type: normal
  points: 5
- name: helm_chart_published
  status: passed
  type: normal
  points: 5
- name: helm_deploy
  status: passed
  type: normal
  points: 5
- name: cni_compatible
  status: passed
  type: normal
  points: 5
- name: increase_decrease_capacity
  status: passed
  type: essential
  points: 100
- name: rollback
  status: failed
  type: normal
  points: 0
- name: no_local_volume_configuration
  status: passed
  type: bonus
  points: 1
- name: elastic_volumes
  status: failed
  type: bonus
  points: 0
- name: node_drain
  status: passed
  type: essential
  points: 100
- name: symlink_file_system
  status: passed
  type: normal
  points: 5
- name: privilege_escalation
  status: failed
  type: normal
  points: 0
- name: insecure_capabilities
  status: passed
  type: normal
  points: 5
- name: resource_policies
  status: passed
  type: essential
  points: 100
- name: linux_hardening
  status: failed
  type: bonus
  points: 0
- name: ingress_egress_blocked
  status: failed
  type: bonus
  points: 0
- name: host_pid_ipc_privileges
  status: passed
  type: normal
  points: 5
- name: non_root_containers
  status: failed
  type: essential
  points: 0
- name: privileged_containers
  status: passed
  type: essential
  points: 100
- name: immutable_file_systems
  status: failed
  type: bonus
  points: 0
- name: hostpath_mounts
  status: passed
  type: essential
  points: 100
- name: container_sock_mounts
  status: passed
  type: essential
  points: 100
- name: external_ips
  status: passed
  type: normal
  points: 5
- name: selinux_options
  status: na
  type: essential
  points: 0
- name: sysctls
  status: passed
  type: normal
  points: 5
- name: host_network
  status: passed
  type: normal
  points: 5
- name: service_account_mapping
  status: failed
  type: normal
  points: 0
- name: application_credentials
  status: passed
  type: normal
  points: 5
- name: nodeport_not_used
  status: passed
  type: normal
  points: 5
- name: hostport_not_used
  status: passed
  type: essential
  points: 100
- name: hardcoded_ip_addresses_in_k8s_runtime_configuration
  status: passed
  type: essential
  points: 100
- name: secrets_used
  status: skipped
  type: bonus
  points: 0
- name: immutable_configmap
  status: failed
  type: bonus
  points: 0
- name: require_labels
  status: passed
  type: normal
  points: 5
- name: latest_tag
  status: passed
  type: essential
  points: 100
- name: default_namespace
  status: passed
  type: normal
  points: 5
- name: log_output
  status: passed
  type: essential
  points: 100
- name: prometheus_traffic
  status: skipped
  type: bonus
  points: 0
- name: open_metrics
  status: skipped
  type: bonus
  points: 0
- name: routed_logs
  status: skipped
  type: bonus
  points: 0
- name: tracing
  status: skipped
  type: bonus
  points: 0
- name: reasonable_image_size
  status: passed
  type: normal
  points: 5
- name: reasonable_startup_time
  status: passed
  type: normal
  points: 5
- name: single_process_type
  status: passed
  type: essential
  points: 100
- name: service_discovery
  status: passed
  type: bonus
  points: 1
- name: shared_database
  status: skipped
  type: normal
  points: 0
- name: pod_network_latency
  status: passed
  type: bonus
  points: 1
- name: pod_network_corruption
  status: passed
  type: bonus
  points: 1
- name: disk_fill
  status: passed
  type: normal
  points: 5
- name: pod_delete
  status: passed
  type: normal
  points: 5
- name: pod_memory_hog
  status: passed
  type: normal
  points: 5
- name: pod_io_stress
  status: passed
  type: bonus
  points: 1
- name: pod_dns_error
  status: skipped
  type: bonus
  points: 0
- name: pod_network_duplication
  status: passed
  type: bonus
  points: 1
- name: liveness
  status: passed
  type: essential
  points: 100
- name: readiness
  status: passed
  type: essential
  points: 100
maximum_points: 1521
total_passed: 38 of 43
essential_passed: 13 of 14
```
