### ISSUE TITLE
[Research] Test Pantheon Tech's lighty-rcgnmi package (v16.1.0) with the cnf-testsuite

### ISSUE THREAD

**Issue by HashNuke** [cncf/cnf-testsuite#1562]
## Description
* Create a cnf-testsuite config file for the [lighty-rcgnmi package v16.1.0]
* Test with the cnf-testsuite following the [v1 cert instructions](https://github.com/cncf/cnf-certification/blob/main/instructions.md).
* Share the test results on the ticket.
* Request peer review.

## `cnf-testsuite.yml` (testsuite config file)

```yaml
---
release_name: lighty-rcgnmi
helm_install_namespace: cnfspace

helm_repository:
  name: pantheontech
  repo_url: "https://pantheontech.github.io/helm-charts"
helm_chart: "pantheontech/lighty-rcgnmi-app-helm"
```

With the above testsuite config run the following command:

```shell
# Setup the CNF on the cluster
./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml

# Run the certification
./cnf-testsuite cert
```

## Essential tests that could be resolved for the CNF

* FAILED `single_process_type`
  * Recommendation: Using `exec` might help remove the parent process after executing the `java` command.
* FAILED `liveness`
  * Recommendation: Add liveness probe to deployment spec.
* FAILED `readiness`
  * Recommendation: Add readiness probe to deployment spec.
* FAILED `resource_policies`
  * Recommendation: Define resource limits in the deployment spec.

**Comment by HashNuke** [comment]
Notes about testing this CNF is available in the team hackmd [here](https://hackmd.io/GMCRKyoSTomnnUUINTr7sA)

**Comment by HashNuke** [comment]
@lixuna I've added more notes to the hackmd doc after looking into the failures with the essential tests. Moving this to peer review.

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/issues/1561#issuecomment-1190452914 8 of 14 essential passed but shouldn't it be 9 of 14 since selinux_options skipped or n/a and you only have listed 5 FAILS in the hackmd?

@HashNuke @taylor @lixuna

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/issues/1570  should address the hardcoded_ip test failures these are getting.

**Comment by agentpoyo** [comment]
I'm going to test these with a multi-node cluster along with your hardcoded_ip updates to see if they reach the 10+ essential tests pass threshold.

**Comment by agentpoyo** [comment]
This now passes 11 of 14 essential tests with the hardcoded_ip fix that was pushed to the `main` branch:

results file:
```
---
name: cnf testsuite
status: 
command: /home/pair/workspace/drew/cnf-testsuite/cnf-testsuite cert
points: 1189
exit_code: 0
items:
- name: helm_chart_valid
  status: passed
  type: normal
  points: 5
- name: helm_chart_published
  status: passed
  type: normal
  points: 5
- name: helm_deploy
  status: passed
  type: normal
  points: 5
- name: cni_compatible
  status: failed
  type: normal
  points: 0
- name: increase_decrease_capacity
  status: passed
  type: essential
  points: 100
- name: rollback
  status: failed
  type: normal
  points: 0
- name: no_local_volume_configuration
  status: passed
  type: bonus
  points: 1
- name: elastic_volumes
  status: failed
  type: bonus
  points: 0
- name: node_drain
  status: passed
  type: essential
  points: 100
- name: symlink_file_system
  status: passed
  type: normal
  points: 5
- name: privilege_escalation
  status: passed
  type: normal
  points: 5
- name: insecure_capabilities
  status: passed
  type: normal
  points: 5
- name: resource_policies
  status: failed
  type: essential
  points: 0
- name: linux_hardening
  status: passed
  type: bonus
  points: 1
- name: ingress_egress_blocked
  status: failed
  type: bonus
  points: 0
- name: host_pid_ipc_privileges
  status: passed
  type: normal
  points: 5
- name: non_root_containers
  status: passed
  type: essential
  points: 100
- name: privileged_containers
  status: passed
  type: essential
  points: 100
- name: immutable_file_systems
  status: failed
  type: bonus
  points: 0
- name: hostpath_mounts
  status: passed
  type: essential
  points: 100
- name: container_sock_mounts
  status: passed
  type: essential
  points: 100
- name: external_ips
  status: passed
  type: normal
  points: 5
- name: selinux_options
  status: na
  type: essential
  points: 0
- name: sysctls
  status: passed
  type: normal
  points: 5
- name: host_network
  status: passed
  type: normal
  points: 5
- name: service_account_mapping
  status: failed
  type: normal
  points: 0
- name: application_credentials
  status: passed
  type: normal
  points: 5
- name: nodeport_not_used
  status: failed
  type: normal
  points: 0
- name: hostport_not_used
  status: passed
  type: essential
  points: 100
- name: hardcoded_ip_addresses_in_k8s_runtime_configuration
  status: passed
  type: essential
  points: 100
- name: secrets_used
  status: skipped
  type: bonus
  points: 0
- name: immutable_configmap
  status: failed
  type: bonus
  points: 0
- name: require_labels
  status: passed
  type: normal
  points: 5
- name: latest_tag
  status: passed
  type: essential
  points: 100
- name: default_namespace
  status: passed
  type: normal
  points: 5
- name: log_output
  status: passed
  type: essential
  points: 100
- name: prometheus_traffic
  status: skipped
  type: bonus
  points: 0
- name: open_metrics
  status: skipped
  type: bonus
  points: 0
- name: routed_logs
  status: skipped
  type: bonus
  points: 0
- name: tracing
  status: skipped
  type: bonus
  points: 0
- name: reasonable_image_size
  status: passed
  type: normal
  points: 5
- name: reasonable_startup_time
  status: passed
  type: normal
  points: 5
- name: single_process_type
  status: passed
  type: essential
  points: 100
- name: service_discovery
  status: passed
  type: bonus
  points: 1
- name: shared_database
  status: skipped
  type: normal
  points: 0
- name: pod_network_latency
  status: failed
  type: bonus
  points: 0
- name: pod_network_corruption
  status: failed
  type: bonus
  points: 0
- name: disk_fill
  status: failed
  type: normal
  points: 0
- name: pod_delete
  status: passed
  type: normal
  points: 5
- name: pod_memory_hog
  status: passed
  type: normal
  points: 5
- name: pod_io_stress
  status: passed
  type: bonus
  points: 1
- name: pod_dns_error
  status: skipped
  type: bonus
  points: 0
- name: pod_network_duplication
  status: failed
  type: bonus
  points: 0
- name: liveness
  status: failed
  type: essential
  points: 0
- name: readiness
  status: failed
  type: essential
  points: 0
maximum_points: 1519
total_passed: 32 of 41
essential_passed: 11 of 14
```

Screenshot:
![pantheon_lightly-rcgnmi_11-14essentials_passed](https://user-images.githubusercontent.com/14348948/181052410-a6400b5d-3399-4d6a-92d0-d82768dd5771.png)
