### ISSUE TITLE
[Research] Test Linkerd2 for the test-suite cert 

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1628]
Description

- Create a cnf-testsuite config file for the latest version of Linkerd.
- Test Linkerd with the cnf-testsuite following the [cert instructions](https://github.com/cncf/cnf-certification/blob/main/instructions.md).
- Share the test results on the ticket.
- Request peer review.

**Comment by denverwilliams** [comment]
```
pair@cnfdev03:~/workspace/denver/cnf-testsuite$ ./cnf-testsuite cert                                                                                                                                                                                                                                                                                                                                                                                                                      
Compatibility, Installability & Upgradability Tests                                                                                                                                                                                                                                                                                                                                                                                                                                       
Successfully created directories for cnf-testsuite                                                                                                                                                                                                                                                                                                                                                                                                                                        
✔️  PASSED: Helm Chart exported_chart Lint Passed ⎈📝☑️                                                                                                                                                                                                                                                                                                                                                                                                                                     
✔️  PASSED: Published Helm Chart Found ⎈📦🌐                                                                                                                                                                                                                                                                                                                                                                                                                                               
✔️  PASSED: Helm deploy successful ⎈🚀                                                                                                                                                                                                                                                                                                                                                                                                                                                     
E, [2022-09-09 17:51:47 -04:00 #764622] ERROR -- cnf-testsuite: Helm install error: execution error at (linkerd-control-plane/templates/identity.yaml:19:21): Please provide the identity issuer certificate                                                                                                                                                                                                                                                                              
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/helm/helm.cr:407:7 in 'install'                                                                                                                                                                                                                                                                                                                                                                                       
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: src/tasks/utils/cnf_manager.cr:1082:24 in 'cnf_to_new_cluster'                                                                                                                                                                                                                                                                                                                                                            
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: src/tasks/workload/compatibility.cr:628:27 in '->'                                                                                                                                                                                                                                                                                                                                                                        
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: /home/pair/.crenv/versions/1.0.0/share/crystal/src/primitives.cr:255:3 in 'all_cnfs_task_runner'                                                                                                                                                                                                                                                                                                                          
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: src/tasks/utils/task.cr:19:9 in 'task_runner'                                                                                                                                                                                                                                                                                                                                                                             
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: src/tasks/workload/compatibility.cr:611:3 in '->'                                                                                                                                                                                                                                                                                                                                                                         
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: /home/pair/.crenv/versions/1.0.0/share/crystal/src/primitives.cr:255:3 in 'call'                                                                                                                                                                                                                                                                                                                                          
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam/execution.cr:20:7 in 'invoke'                                                                                                                                                                                                                                                                                                                                                                             
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam/task.cr:44:29 in 'call'                                                                                                                                                                                                                                                                                                                                                                                   
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam/execution.cr:20:7 in 'invoke'                                                                                                                                                                                                                                                                                                                                                                             
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam/task.cr:44:29 in 'call'                                                                                                                                                                                                                                                                                                                                                                                   
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam/execution.cr:20:7 in 'invoke'                                                                                                                                                                                                                                                                                                                                                                             
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam.cr:35:5 in 'invoke'                                                                                                                                                                                                                                                                                                                                                                                       
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: lib/sam/src/sam.cr:53:7 in 'process_tasks'                                                                                                                                                                                                                                                                                                                                                                                
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: src/cnf-testsuite.cr:129:3 in '__crystal_main'                                                                                                                                                                                                                                                                                                                                                                            
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: /home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: /home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:96:7 in 'main'
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: /home/pair/.crenv/versions/1.0.0/share/crystal/src/crystal/main.cr:119:3 in 'main'
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: __libc_start_main
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: _start
E, [2022-09-09 17:51:48 -04:00 #764622] ERROR -- cnf-testsuite: ???
✔️  PASSED: Replicas increased to 3 and decreased to 1 📦📉
✖️  FAILED: CNF Rollback Failed
Compatibility, installability, and upgradeability results: 4 of 6 tests passed

State Tests
E, [2022-09-09 17:51:50 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✔️  PASSED: local storage configuration volumes not found 🖥️  💾
⏭️  SKIPPED: No volumes used 🧫
E, [2022-09-09 17:51:51 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  🏆 FAILED: node_drain chaos test failed 🗡️💀♻️
State results: 1 of 2 tests passed

Security Tests
E, [2022-09-09 17:51:53 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✔️  PASSED: No containers allow a symlink attack 🔓🔑
✔️  PASSED: No containers that allow privilege escalation were found 🔓🔑
✔️  PASSED: Containers with insecure capabilities were not found 🔓🔑
✔️  🏆 PASSED: Containers have resource limits defined 🔓🔑
✔️  PASSED: Security services are being used to harden applications 🔓🔑
✔️  PASSED: Ingress and Egress traffic blocked on pods 🔓🔑
✔️  PASSED: No containers with hostPID and hostIPC privileges 🔓🔑
✔️  🏆 PASSED: Containers are running with non-root user with non-root group membership 🔓🔑
✔️  🏆 PASSED: No privileged containers were found 🔓🔑
✔️  PASSED: Containers have immutable file systems 🔓🔑
✔️  PASSED: Containers do not have hostPath mounts 🔓🔑
✔️  🏆 PASSED: Container engine daemon sockets are not mounted as volumes 🔓🔑
✔️  PASSED: Services are not using external IPs 🔓🔑
⏭️  🏆 N/A: Pods are not using SELinux 🔓🔑
✔️  PASSED: No restricted values found for sysctls 🔓🔑
✔️  PASSED: No host network attached to pod 🔓🔑
✔️  PASSED: No service accounts automatically mapped 🔓🔑
✔️  PASSED: No applications credentials in configuration files 🔓🔑
Security results: 17 of 17 tests passed

Configuration Tests
✖️  FAILED: NodePort is being used
E, [2022-09-09 17:52:12 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  🏆 FAILED: HostPort is being used
E, [2022-09-09 17:52:13 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✔️  🏆 PASSED: No hard-coded IP addresses found in the runtime K8s configuration
⏭  SKIPPED: Secrets not used 🧫

To address this issue please see the USAGE.md documentation

E, [2022-09-09 17:52:20 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: Found mutable configmap(s) ⚖️
E, [2022-09-09 17:52:21 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✔️  PASSED: Pods have the app.kubernetes.io/name label 🏷️✔️
✔️  🏆 PASSED: Container images are not using the latest tag 🏷️✔️
✔️  PASSED: default namespace is not being used 🏷️✔️
Configuration results: 4 of 6 tests passed

Observability and Diagnostics Tests
✖️  🏆 FAILED: Resources do not output logs to stdout and stderr 📶☠️
E, [2022-09-09 17:52:26 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
⏭️  SKIPPED: Prometheus server not found 📶☠️
⏭️  SKIPPED: Prometheus traffic not configured 📶☠️
⏭️  SKIPPED: Fluentd or FluentBit not configured 📶☠️
⏭️  SKIPPED: Jaeger not configured ⎈🚀
Observability and diagnostics results: 0 of 1 tests passed

Microservice Tests
✖️  FAILED: Image size too large 🦖 ⚖️👀
E, [2022-09-09 17:52:44 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✔️  PASSED: CNF had a reasonable startup time 🚀
✖️  🏆 FAILED: More than one process type used 🦖 ⚖️👀
E, [2022-09-09 17:53:03 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: No containers exposed as a service 🦖 ⚖️👀
⏭️  SKIPPED: [shared_database] No MariaDB containers were found
Microservice results: 1 of 4 tests passed

Reliability, Resilience, and Availability Tests
✖️  FAILED: pod_network_latency chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:05 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: pod_network_corruption chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:06 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: disk_fill chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:06 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: pod_delete chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:06 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: pod_memory_hog chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:07 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  FAILED: pod_io_stress chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:07 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
⏭️  SKIPPED: pod_dns_error docker runtime not found 🗡️💀♻️
✖️  FAILED: pod_network_duplication chaos test failed 🗡️💀♻️
E, [2022-09-09 17:53:08 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  🏆 FAILED: No livenessProbe found ⎈🧫
E, [2022-09-09 17:53:09 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
✖️  🏆 FAILED: No readinessProbe found ⎈🧫
Reliability, resilience, and availability results: 0 of 5 tests passed

RESULTS SUMMARY
  - 27 of 41 total tests passed
  - 8 of 14 essential tests passed
Results have been saved to results/cnf-testsuite-results-20220909-175108-504.yml
E, [2022-09-09 17:53:09 -04:00 #764622] ERROR -- cnf-testsuite: no resource names found
```


```
pair@cnfdev03:~/workspace/denver/cnf-testsuite$ cat results/cnf-testsuite-results-20220909-175108-504.yml                                                                                                                                                                                                                                                                                                                                                                                 
---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
name: cnf testsuite                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
status:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
command: /home/pair/workspace/denver/cnf-testsuite/cnf-testsuite cert                                                                                                                                                                                                                                                                                                                                                                                                                     
points: 879                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
exit_code: 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
items:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
- name: helm_chart_valid                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: helm_chart_published                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: helm_deploy                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: increase_decrease_capacity                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 100                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
- name: rollback                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  status: failed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: no_local_volume_configuration                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: bonus                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  points: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: elastic_volumes                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  status: skipped                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  type: bonus                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  points: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: node_drain                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  status: failed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: symlink_file_system                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: privilege_escalation                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: insecure_capabilities                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: resource_policies                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 100                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
- name: linux_hardening                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: bonus                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  points: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: ingress_egress_blocked                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: bonus                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  points: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: host_pid_ipc_privileges                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: normal                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  points: 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: non_root_containers                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 100                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
- name: privileged_containers                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 100                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
- name: immutable_file_systems                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: bonus                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  points: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
- name: hostpath_mounts                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  status: passed                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  type: essential                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  points: 100                                                                                                                                                                                 
- name: container_sock_mounts
  status: passed
  type: essential
  points: 100
- name: external_ips
  status: passed
  type: normal
  points: 5
- name: selinux_options
  status: na
  type: essential
  points: 0
- name: sysctls
  status: passed
  type: normal
  points: 5
- name: host_network
  status: passed
  type: normal
  points: 5
- name: service_account_mapping
  status: passed
  type: normal
  points: 5
- name: application_credentials
  status: passed
  type: normal
  points: 5
- name: nodeport_not_used
  status: failed
  type: normal
  points: 0
- name: hostport_not_used
  status: failed
  type: essential
  points: 0
- name: hardcoded_ip_addresses_in_k8s_runtime_configuration
  status: passed
  type: essential
  points: 100
- name: secrets_used
  status: skipped
  type: bonus
  points: 0
- name: immutable_configmap
  status: failed
  type: bonus
  points: 0
- name: require_labels
  status: passed
  type: normal
  points: 5
- name: latest_tag
  status: passed
  type: essential
  points: 100
- name: default_namespace
  status: passed
  type: normal
  points: 5
- name: log_output
  status: failed
  type: essential
  points: 0
- name: prometheus_traffic
  status: skipped
  type: bonus
  points: 0
- name: open_metrics
  status: skipped
  type: bonus
  points: 0
- name: routed_logs
  status: skipped
  type: bonus
  points: 0
- name: tracing
  status: skipped
  type: bonus
  points: 0
- name: reasonable_image_size
  status: failed
  type: normal
  points: 0
- name: reasonable_startup_time
  status: passed
  type: normal
  points: 5
- name: single_process_type
  status: failed
  type: essential
  points: 0
- name: service_discovery
  status: failed
  type: bonus
  points: 0
- name: shared_database
  status: skipped
  type: normal
  points: 0
- name: pod_network_latency
  status: failed
  type: bonus
  points: 0
- name: pod_network_corruption
  status: failed
  type: bonus
  points: 0
- name: disk_fill
  status: failed
  type: normal
  points: 0
- name: pod_delete
  status: failed
  type: normal
  points: 0
- name: pod_memory_hog
  status: failed
  type: normal
  points: 0
- name: pod_io_stress
  status: failed
  type: bonus
  points: 0
- name: pod_dns_error
  status: skipped
  type: bonus
  points: 0
- name: pod_network_duplication
  status: failed
  type: bonus
  points: 0
- name: liveness
  status: failed
  type: essential
  points: 0
- name: readiness
  status: failed
  type: essential
  points: 0
maximum_points: 1519
total_passed: 27 of 41
essential_passed: 8 of 14
```
