### ISSUE TITLE
[BUG] Investigate using non-default chart versions - passing helm arguments

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1657]
**Describe the bug**

https://github.com/cncf/cnf-certification/pull/34 - Investigate & document usage of helm arguments for installing CNFs.

**To Reproduce**

From provided [CNF testsuite configuration](https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md) I was not able to configure testsuite to use specific lighty-rcgnmi-app version from published [helm repository](https://github.com/PANTHEONtech/helm-charts). (With configuration from https://github.com/cncf/cnf-testsuite/issues/1562 it takes version 16.1.0)
e.g.: helm install lighty-rcgnmi-app pantheon-helm-repo/lighty-rcgnmi-app-helm --version 16.2.0.
If there is a way how to do it, feel free to guide me or fix it directly in PR.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by denverwilliams** [comment]
Confirm that we can change the helm chart version by using our 'helm_values' configuration field. 

```
☺ ➔  cat prometheus/cnf-testsuite.yml 
---
release_name: prometheus
helm_repository:
  name: prometheus-community
  repo_url: https://prometheus-community.github.io/helm-charts
helm_chart: prometheus-community/prometheus
helm_values: --version 15.11.0
allowlist_helm_chart_container_names: [falco, node-cache, nginx, coredns, calico-node, kube-proxy, nginx-proxy]
```

```
☺ ➔  kubectl get pods prometheus-server-5b677dd7f-f884q -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-09-23T19:40:59Z"
  generateName: prometheus-server-5b677dd7f-
  labels:
    app: prometheus
    chart: prometheus-15.11.0
    component: server
    heritage: Helm
    pod-template-hash: 5b677dd7f
    release: prometheus
```

**Comment by denverwilliams** [comment]
Documentation Update: https://github.com/cncf/cnf-testsuite/pull/1656

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I configure my cnf-testsuite.yml config file, I should be able to specify `helm-values: --version x.x.x` to override any defaults on the repo for helm chart versions.
- [ ] I can see a successful `cnf_setup` specifying chart value version in my cnf yml config here.

**Comment by agentpoyo** [comment]
```
root@cncf-testsuite-test1:~/cnf-testsuite# ./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml 
Successfully created directories for cnf-testsuite
cnf-testsuite namespace already exists on the Kubernetes cluster
cnf setup online mode
Successfully setup coredns
cnf setup online mode complete
root@cncf-testsuite-test1:~/cnf-testsuite# kubectl get pods --all-namespaces
NAMESPACE            NAME                                          READY   STATUS    RESTARTS   AGE
cnf-testsuite        cluster-tools-d6bkq                           1/1     Running   0          15s
cnf-testsuite        cluster-tools-f8pm9                           1/1     Running   0          15s
cnf-testsuite        cluster-tools-r4m27                           1/1     Running   0          15s
cnfspace             coredns-coredns-7f4b77bf96-dztz4              0/1     Running   0          11s
```

**Comment by agentpoyo** [comment]
```
root@cncf-testsuite-test1:~/cnf-testsuite# cat cnf-testsuite.yml 
---
release_name: coredns
service_name: coredns-coredns 
helm_repository:
  name: stable 
  repo_url: https://coredns.github.io/helm
helm_chart: coredns/coredns
helm_values: --version 1.19.4
helm_install_namespace: cnfspace
container_names: 
  - name: coredns 
    rolling_update_test_tag: "1.9.3"
    rolling_downgrade_test_tag: 1.9.3
    rolling_version_change_test_tag: 1.9.3
    rollback_from_tag: 1.9.3
```

![1657_chart_values_config](https://user-images.githubusercontent.com/14348948/192627442-c7dc7c2f-79fb-4149-96c4-b6856b116686.png)
