### ISSUE TITLE
[BUG] Node Drain issues

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1727]
**Describe the bug**
Not really a bug so much as a better understanding of why node drain is failing without any noticeable errors.
Could be a problem with trying to run cnf-testsuite in a kind env

***Logs***

***Node Drain Pod***
`time="2023-01-24T21:31:53Z" level=info msg="[Confirmation]: node-drain chaos has been injected successfully"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" container=chf Pod=chf-cnf-586f874bfb-trm9p Readiness=true
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" Pod=chf-cnf-586f874bfb-trm9p Readiness=true container=chf-leader-elect
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" Readiness=true container=chf Pod=chf-cnf-586f874bfb-wqllj
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are
 as follows" Readiness=true container=chf-leader-elect Pod=chf-cnf-586f874bfb-wqllj
time="2023-01-24T21:31:55Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2023-01-24T21:31:55Z" level=info msg="[Status]: The status of Pods are as follows" Status=Running Pod=chf-cnf-586f874bfb-trm9p
time="2023-01-24T21:31:55Z" level=info msg="[Status]: The status of Pods are as follows" Pod=chf-cnf-586f874bfb-wqllj Status=Running
time="2023-01-24T21:31:57Z" level=info msg="[Status]: Getting the status of target nodes"
time="2023-01-24T21:31:57Z" level=info msg="The Node status are as follows" Ready=true Node=ktx-ancient-architect-worker2
time="2023-01-24T21:31:57Z" level=info msg="[The End]: Updating the chaos result of node-drain experiment (EOT)"`

***CNF-Testsuite Output***
2023-01-24 16:32:11.965  INFO --- c.m.k.Context                            :  EVENT: SUCCESS 2023-01-24T16:26:42.767-0500 (5m) Competed CNF Test Suite node_drain Command for testCHF
✖️  🏆 FAILED: node_drain chaos test failed 🗡️💀♻️

***Kind Config***
[kind-config.zip](https://github.com/cncf/cnf-testsuite/files/10494273/kind-config.zip)

***Images***
![Nodes from Lens](https://user-images.githubusercontent.com/99511419/214428240-f9f112af-ae1b-40a4-8bed-05e7d73affca.png)
![Pods from Lens](https://user-images.githubusercontent.com/99511419/214428246-181e59e2-060e-49c4-a295-c0993a29df6e.png)

**Comment by lixuna** [comment]
@HashNuke were you able to recreate this issue?

**Comment by HashNuke** [comment]
Attempted to reproduce this issue with a sample CNF. The `node_drain` test output seems fine.
I used a variation of the kind config attached on the ticket description (I've posted that below).

Please let us know if there is any other config/info we can use to reproduce this issue.

## Screenshot of `node_drain` test output

<img width="1327" alt="CleanShot 2023-06-27 at 19 48 48@2x" src="https://github.com/cncf/cnf-testsuite/assets/84005/9527334c-3cf1-4d04-bfd4-23da416db32e">

## Commands used to run the test

```shell
export KIND_CLUSTER_NAME="test-1727"
export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig"
kind create cluster --name $KIND_CLUSTER_NAME \
--kubeconfig $KUBECONFIG \
--config kind-config.yml

./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-coredns-cnf
./cnf-testsuite node_drain
```

## kind config used

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-image-registry:5000"]
      endpoint = ["localhost:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
```
