### ISSUE TITLE
[BUG] Litmus tests failing

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1829]
**Describe the bug**
Getting
```
 KubectlClient::Apply.file stderr: error: error parsing /home/pair/.cnf-testsuite/tools/chaos-experiments/pod_network_latency_experiment.yaml: error
 converting YAML to JSON: yaml: mapping values are not allowed in this context 
```
in the output
**To Reproduce**

LOG_LEVEL=info crystal spec spec/workload/resilience/pod_network_latency_spec.cr

**Expected behavior**
Passing spec

**Comment by rich-l** [comment]
Log output
I, [2023-10-03 07:23:25 -07:00 #3175294]  INFO -- cnf-testsuite: KubectlClient::Get.replica_count command: kubectl get Deployment --namespace=litmus litmus -o=jsonpath='{.status.unavailableReplicas}'
I, [2023-10-03 07:23:25 -07:00 #3175294]  INFO -- cnf-testsuite: KubectlClient::Get.replica_count stderr: Error from server (NotFound): deployments.apps "litmus" not found

**Comment by agentpoyo** [comment]
@rich-l ,

Can you share your cnf-testsuite.yml config file? I can't seem to reproduce what you are seeing on a fresh kind cluster and using coredns to test with. The only kubectl get Deployment command in my debug are the name of my own coredns namespace I'm using in the cnf-testsuite.yml config file.

Thanks

**Comment by rich-l** [comment]
@agentpoyo cnf-testsuite.yaml
```
release_name: f5edgefw
allowlist_helm_chart_container_names: [f5-tmm]
helm_directory: f5ingress
helm_repository:
  name: cnf
  repo_url: https://wisespacr.azurecr.io/cnf
helm_install_namespace: cncf-cert
helm_values: "-f ./f5ingress-values.yaml"
```
